// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Cx = require('rescript-classnames/src/Cx.js');
var React = require('react');
var EatStatusModuleCss = require('./eatStatus.module.css');

var styles = EatStatusModuleCss;

function EatStatus(Props) {
  var fastHasStarted = Props.fastHasStarted;
  var variant = fastHasStarted
    ? {
        text: "CAN'T EAT",
        colourClass: styles.red
      }
    : {
        text: 'CAN EAT',
        colourClass: styles.green
      };
  var dotClasses = Cx.cx([styles.dot, variant.colourClass]);
  return React.createElement(
    'div',
    {
      className: styles.container
    },
    React.createElement('div', {
      className: dotClasses
    }),
    React.createElement('h3', undefined, variant.text)
  );
}

var make = EatStatus;

exports.styles = styles;
exports.make = make;
/* styles Not a pure module */
