// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require('react');
var EatStatusModuleCss = require('./eatStatus.module.css');

var styles = EatStatusModuleCss;

function EatStatus(Props) {
  var fastHasStarted = Props.fastHasStarted;
  var options = fastHasStarted
    ? {
        text: "CAN'T EAT",
        colourClass: styles.red
      }
    : {
        text: 'CAN EAT',
        colourClass: styles.green
      };
  var lightClasses = styles.light + ' ' + options.colourClass;
  return React.createElement(
    'div',
    {
      className: styles.container
    },
    React.createElement('div', {
      className: lightClasses
    }),
    React.createElement('h3', undefined, options.text)
  );
}

var make = EatStatus;

exports.styles = styles;
exports.make = make;
/* styles Not a pure module */
