// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Cx = require('rescript-classnames/src/Cx.js');
var React = require('react');
var LocationPillModuleCss = require('./locationPill.module.css');

var styles = LocationPillModuleCss;

function LocationPill$ButtonVariant(Props) {
  var text = Props.text;
  var onClick = Props.onClick;
  return React.createElement(
    'button',
    {
      className: Cx.cx([styles.container, styles.button]),
      onClick: onClick
    },
    React.createElement('p', undefined, text)
  );
}

var ButtonVariant = {
  make: LocationPill$ButtonVariant
};

function LocationPill$DivVariant(Props) {
  var text = Props.text;
  return React.createElement(
    'div',
    {
      className: styles.container
    },
    React.createElement('p', undefined, text)
  );
}

var DivVariant = {
  make: LocationPill$DivVariant
};

function LocationPill(Props) {
  var text = Props.text;
  var onClick = Props.onClick;
  if (onClick !== undefined) {
    return React.createElement(LocationPill$ButtonVariant, {
      text: text,
      onClick: onClick
    });
  } else {
    return React.createElement(LocationPill$DivVariant, {
      text: text
    });
  }
}

var make = LocationPill;

exports.styles = styles;
exports.ButtonVariant = ButtonVariant;
exports.DivVariant = DivVariant;
exports.make = make;
/* styles Not a pure module */
