// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var allowed = [
  {
    title: 'Using miswak or toothbrush (even with toothpaste)',
    description: 'Be careful not to swallow or overdo it'
  },
  {
    title: 'Eating or drinking unintentionally',
    description:
      'i.e. forgetting that you were fasting. But you must stop as soon as you realise and continue with your fast'
  },
  {
    title: 'Rinsing the mouth or nostrils with water',
    description: 'Provided it is not overdone (so as to avoid swallowing water)'
  },
  {
    title: 'Swallowing your own saliva',
    description: undefined
  },
  {
    title: 'Using perfumes, wearing contact lenses or using eye drops',
    description: undefined
  }
];

var disallowed = [
  {
    title: 'Eating or drinking deliberately',
    description:
      'This includes taking any non-nourishing items by mouth or nose'
  },
  {
    title: 'The beginning of menstrual or post-childbirth bleeding',
    description: 'Even if it occurs in the last moments before sunset'
  },
  {
    title:
      'Eating, drinking, smoking or having sexual intercourse after Fajr (dawn) on the mistaken assumption that it is not Fajr time yet',
    description:
      'Similarly, engaging in these acts before Maghrib (sunset) on the mistaken assumption that it is already Maghrib time'
  },
  {
    title: 'Deliberately causing yourself to vomit',
    description: undefined
  }
];

exports.allowed = allowed;
exports.disallowed = disallowed;
/* No side effect */
