// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Cx = require('rescript-classnames/src/Cx.js');
var React = require('react');
var NavBar = require('../../components/navBar/navBar.js');
var RuleList = require('./RuleList.js');
var Container = require('../../components/layout/container.js');
var BackSvg = require('./back.svg');
var Belt_Array = require('rescript/lib/js/belt_Array.js');
var RulesModuleCss = require('./Rules.module.css');
var RescriptReactRouter = require('@rescript/react/src/RescriptReactRouter.js');

var styles = RulesModuleCss;

var backIcon = BackSvg;

function Rules$Note(Props) {
  return React.createElement(
    'div',
    {
      className: Cx.cx([styles.card, styles.note])
    },
    React.createElement(
      'p',
      undefined,
      'This is a quick reference, for the full guide please read: ',
      React.createElement(
        'a',
        {
          href: 'http://www.iccuk.org/downloads/Introduction_to_Fasting.pdf'
        },
        'The Brief Introduction to Ramadan Fasting'
      ),
      '.'
    )
  );
}

var Note = {
  make: Rules$Note
};

function renderRules(ruleSet) {
  return Belt_Array.mapWithIndex(ruleSet, function(i, rule) {
    var text = rule.description;
    var description = text !== undefined ? text : null;
    return React.createElement(
      'li',
      {
        key: String(i),
        className: styles.rule
      },
      React.createElement(
        'p',
        {
          className: styles.title
        },
        rule.title
      ),
      React.createElement(
        'p',
        {
          className: styles.description
        },
        description
      )
    );
  });
}

function Rules(Props) {
  return React.createElement(
    Container.make,
    {
      children: null,
      variant: /* SCROLL */ 2
    },
    React.createElement(NavBar.make, {
      title: 'Fasting Rules',
      icon: backIcon,
      onClick: function(_t) {
        return RescriptReactRouter.push('/');
      }
    }),
    React.createElement(Rules$Note, {}),
    React.createElement(
      'div',
      {
        className: Cx.cx([styles.card, styles.green])
      },
      React.createElement(
        'h2',
        {
          className: styles.heading
        },
        'Things that are ok'
      ),
      React.createElement('ul', undefined, renderRules(RuleList.allowed))
    ),
    React.createElement(
      'div',
      {
        className: Cx.cx([styles.card, styles.red])
      },
      React.createElement(
        'h2',
        {
          className: styles.heading
        },
        'Things that break our fast'
      ),
      React.createElement('ul', undefined, renderRules(RuleList.disallowed))
    )
  );
}

var make = Rules;

exports.styles = styles;
exports.backIcon = backIcon;
exports.Note = Note;
exports.renderRules = renderRules;
exports.make = make;
/* styles Not a pure module */
