// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require('react');
var ButtonModuleCss = require('./button.module.css');

var styles = ButtonModuleCss;

function Button(Props) {
  var children = Props.children;
  var onClick = Props.onClick;
  return React.createElement(
    'button',
    {
      className: styles.container,
      onClick: onClick
    },
    children
  );
}

var make = Button;

exports.styles = styles;
exports.make = make;
/* styles Not a pure module */
