// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require('react');
var Container = require('../layout/container.js');
var IftarScreenModuleCss = require('./iftarScreen.module.css');

var styles = IftarScreenModuleCss;

function make(param) {
  return React.createElement(Container.make, {
    children: React.createElement(
      'div',
      {
        className: styles.container
      },
      React.createElement('h1', undefined, 'Time to break your fast')
    ),
    variant: /* IFTAR_SCREEN */ 1
  });
}

exports.styles = styles;
exports.make = make;
/* styles Not a pure module */
