// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require('react');
var TimeLabelModuleCss = require('./timeLabel.module.css');

var styles = TimeLabelModuleCss;

function TimeLabel(Props) {
  var text = Props.text;
  var time = Props.time;
  return React.createElement(
    'div',
    undefined,
    React.createElement(
      'p',
      {
        className: styles.label
      },
      text
    ),
    React.createElement(
      'p',
      {
        className: styles.time
      },
      time
    )
  );
}

var make = TimeLabel;

exports.styles = styles;
exports.make = make;
/* styles Not a pure module */
