// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require('react');
var InfoRowModuleCss = require('./infoRow.module.css');

var styles = InfoRowModuleCss;

function InfoRow(Props) {
  var leftComponent = Props.leftComponent;
  var rightComponent = Props.rightComponent;
  return React.createElement(
    'div',
    {
      className: styles.container
    },
    leftComponent,
    React.createElement('div', {
      className: styles.separator
    }),
    rightComponent
  );
}

var make = InfoRow;

exports.styles = styles;
exports.make = make;
/* styles Not a pure module */
