// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require('react');
var Container = require('../layout/container.js');
var EidCardModuleCss = require('./eidCard.module.css');

var styles = EidCardModuleCss;

var partyPopperEmoji = 'https://dsc.cloud/3ca15e/party-popper-emoji.png';

function EidCard(Props) {
  return React.createElement(Container.make, {
    children: React.createElement(
      'div',
      {
        className: styles.container
      },
      React.createElement('h1', undefined, 'Eid Mubarak!'),
      React.createElement('img', {
        className: styles.emoji,
        alt: 'Party popper emoji',
        src: partyPopperEmoji
      }),
      React.createElement(
        'div',
        undefined,
        React.createElement(
          'p',
          undefined,
          'May Allah bless you with a great day!'
        ),
        React.createElement(
          'p',
          undefined,
          'I hope this Ramadan has been beneficial as well as healing. I pray our\n          good acts have been accepted and that we see them continue.'
        ),
        React.createElement(
          'p',
          undefined,
          'I hope FastingTime has been useful, it was a lot of fun to build, so\n          thank you for using it. It means a lot.'
        ),
        React.createElement(
          'p',
          undefined,
          'As always, please keep me in your duas, and see you next Ramadan\n          inshaAllah!'
        ),
        React.createElement(
          'p',
          undefined,
          'JazakAllah khair,',
          React.createElement('br', undefined),
          React.createElement(
            'a',
            {
              href: 'https://github.com/faheempatel'
            },
            'Faheem'
          )
        )
      )
    )
  });
}

var make = EidCard;

exports.styles = styles;
exports.partyPopperEmoji = partyPopperEmoji;
exports.make = make;
/* styles Not a pure module */
