// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Cx = require('rescript-classnames/src/Cx.js');
var React = require('react');
var ContainerModuleCss = require('./container.module.css');

var styles = ContainerModuleCss;

function Container(Props) {
  var children = Props.children;
  var variant = Props.variant;
  var appContainerVariantClassName;
  if (variant !== undefined) {
    switch (variant) {
      case /* HOME_SCREEN */ 0:
        appContainerVariantClassName = styles.homeScreen;
        break;
      case /* IFTAR_SCREEN */ 1:
        appContainerVariantClassName = styles.iftarScreen;
        break;
      case /* SCROLL */ 2:
        appContainerVariantClassName = styles.showScrollbar;
        break;
    }
  } else {
    appContainerVariantClassName = '';
  }
  var appContainerClasses = Cx.cx([
    styles.appContainer,
    appContainerVariantClassName
  ]);
  return React.createElement(
    'div',
    {
      className: styles.container
    },
    React.createElement(
      'div',
      {
        className: appContainerClasses
      },
      children
    )
  );
}

var make = Container;

exports.styles = styles;
exports.make = make;
/* styles Not a pure module */
