// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Cx = require('rescript-classnames/src/Cx.js');
var React = require('react');
var NavBarModuleCss = require('./navBar.module.css');

var styles = NavBarModuleCss;

function NavBar$Icon(Props) {
  var icon = Props.icon;
  var onClick = Props.onClick;
  var className = Props.className;
  return React.createElement('button', {
    className: className,
    style: {
      backgroundImage: 'url(' + icon + ')'
    },
    onClick: onClick
  });
}

var Icon = {
  make: NavBar$Icon
};

function NavBar(Props) {
  var title = Props.title;
  var subtitle = Props.subtitle;
  var icon = Props.icon;
  var variant = Props.variant;
  var onClick = Props.onClick;
  var match = icon !== undefined ? [true, icon] : [false, ''];
  var icon$1 = match[1];
  var hasIcon = match[0];
  var match$1 =
    onClick !== undefined ? [true, onClick] : [false, function(_t) {}];
  var onClick$1 = match$1[1];
  var iconComponent =
    hasIcon && match$1[0]
      ? variant !== undefined
        ? React.createElement(NavBar$Icon, {
            icon: icon$1,
            onClick: onClick$1,
            className: Cx.cx([styles.icon, styles.smallIcon])
          })
        : React.createElement(NavBar$Icon, {
            icon: icon$1,
            onClick: onClick$1,
            className: styles.icon
          })
      : null;
  var titleClasses = Cx.cx([
    styles.titles,
    hasIcon ? styles.titlesWithIcon : ''
  ]);
  return React.createElement(
    'nav',
    {
      className: styles.container
    },
    iconComponent,
    React.createElement(
      'div',
      {
        className: titleClasses
      },
      React.createElement('h4', undefined, title),
      React.createElement('p', undefined, subtitle)
    )
  );
}

var make = NavBar;

exports.styles = styles;
exports.Icon = Icon;
exports.make = make;
/* styles Not a pure module */
