// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require('react');
var NavBar = require('./navBar.js');
var MapPinSvg = require('./map-pin.svg');

var mapPinIcon = MapPinSvg;

function NavBarWithLocationMenu(Props) {
  var title = Props.title;
  var subtitle = Props.subtitle;
  var variant = Props.variant;
  var onClick = Props.onClick;
  return React.createElement(NavBar.make, {
    title: title,
    subtitle: subtitle,
    icon: mapPinIcon,
    variant: variant,
    onClick: onClick
  });
}

var make = NavBarWithLocationMenu;

exports.mapPinIcon = mapPinIcon;
exports.make = make;
/* mapPinIcon Not a pure module */
