// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require('react');
var FooterModuleCss = require('./footer.module.css');

var styles = FooterModuleCss;

function make(param) {
  return React.createElement(
    'div',
    {
      className: styles.container
    },
    React.createElement(
      'p',
      undefined,
      'Made by',
      React.createElement(
        'a',
        {
          href: 'https://github.com/faheempatel'
        },
        'Faheem'
      )
    ),
    React.createElement('p', undefined, 'Please keep me in your duas 🤲🏼 ')
  );
}

exports.styles = styles;
exports.make = make;
/* styles Not a pure module */
